; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35224.0 

	TITLE	D:\工具\ncm\测试区\汇编\ncmmini.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

;	COMDAT ?fil@?1??mainCRTStartup@@9@9
_DATA	SEGMENT
?fil@?1??mainCRTStartup@@9@9 DB 'N', 00H, 'C', 00H, 'M', 00H, 00H, 00H, '*'
	DB	00H, '.', 00H, 'n', 00H, 'c', 00H, 'm', 00H, 00H, 00H, 00H, 00H
	DB	00H, 00H					; `mainCRTStartup'::`2'::fil
_DATA	ENDS
;	COMDAT _MK
CONST	SEGMENT
_MK	DB	023H
	DB	031H
	DB	034H
	DB	06cH
	DB	06aH
	DB	06bH
	DB	05fH
	DB	021H
	DB	05cH
	DB	05dH
	DB	026H
	DB	030H
	DB	055H
	DB	03cH
	DB	027H
	DB	028H
CONST	ENDS
;	COMDAT _CK
CONST	SEGMENT
_CK	DB	068H
	DB	07aH
	DB	048H
	DB	052H
	DB	041H
	DB	06dH
	DB	073H
	DB	06fH
	DB	035H
	DB	06bH
	DB	049H
	DB	06eH
	DB	062H
	DB	061H
	DB	078H
	DB	057H
CONST	ENDS
;	COMDAT _M
CONST	SEGMENT
_M	DB	043H
	DB	054H
	DB	045H
	DB	04eH
	DB	046H
	DB	044H
	DB	041H
	DB	04dH
CONST	ENDS
PUBLIC	_mainCRTStartup
PUBLIC	??_C@_17PJMHNJHG@?$AAA?$AAE?$AAS@		; `string'
PUBLIC	??_C@_1CA@GGHMBPCI@?$AAC?$AAh?$AAa?$AAi?$AAn?$AAi?$AAn?$AAg?$AAM?$AAo?$AAd?$AAe?$AAE?$AAC?$AAB@ ; `string'
PUBLIC	??_C@_1BK@BCJKEJJO@?$AAC?$AAh?$AAa?$AAi?$AAn?$AAi?$AAn?$AAg?$AAM?$AAo?$AAd?$AAe@ ; `string'
PUBLIC	??_C@_1BK@GPNIFMAA@?$AAO?$AAb?$AAj?$AAe?$AAc?$AAt?$AAL?$AAe?$AAn?$AAg?$AAt?$AAh@ ; `string'
PUBLIC	??_C@_04FJJKFLMH@flac@				; `string'
PUBLIC	??_C@_03LHGNACFN@mp3@				; `string'
PUBLIC	??_C@_03EIHDBIJH@m4a@				; `string'
PUBLIC	??_C@_03PDOMKJON@bin@				; `string'
PUBLIC	??_C@_06FOCAFPGH@artist@			; `string'
PUBLIC	??_C@_0BH@LNMJBFMK@163?5key?$CIDon?8t?5modify?$CJ?3@ ; `string'
PUBLIC	??_C@_06EEHJBIEA@music?3@			; `string'
PUBLIC	??_C@_09MBFMNLN@musicName@			; `string'
PUBLIC	??_C@_05MCBBJIDG@album@				; `string'
PUBLIC	??_C@_09NGJJJBGE@image?1png@			; `string'
PUBLIC	??_C@_0L@PJKHLKFB@image?1jpeg@			; `string'
PUBLIC	??_C@_04JEJHKEED@TIT2@				; `string'
PUBLIC	??_C@_04IPEPCGNC@TPE1@				; `string'
PUBLIC	??_C@_04GMCJAHJC@TALB@				; `string'
PUBLIC	??_C@_17EGHIAIGL@?$AAN?$AAC?$AAM@		; `string'
PUBLIC	??_C@_15PMCGDJNJ@?$AAO?$AAK@			; `string'
PUBLIC	??_C@_19JDHDJODM@?$AAF?$AAA?$AAI?$AAL@		; `string'
EXTRN	__imp__CreateFileW@28:PROC
EXTRN	__imp__GetFileSizeEx@8:PROC
EXTRN	__imp__ReadFile@20:PROC
EXTRN	__imp__WriteFile@20:PROC
EXTRN	__imp__CloseHandle@4:PROC
EXTRN	__imp__HeapAlloc@12:PROC
EXTRN	__imp__HeapFree@12:PROC
EXTRN	__imp__GetProcessHeap@0:PROC
EXTRN	__imp__ExitProcess@4:PROC
EXTRN	__imp__MessageBoxW@16:PROC
EXTRN	_BCryptOpenAlgorithmProvider@16:PROC
EXTRN	_BCryptGetProperty@24:PROC
EXTRN	_BCryptSetProperty@20:PROC
EXTRN	_BCryptCloseAlgorithmProvider@8:PROC
EXTRN	_BCryptGenerateSymmetricKey@28:PROC
EXTRN	_BCryptDecrypt@40:PROC
EXTRN	_BCryptDestroyKey@4:PROC
EXTRN	__imp__GetOpenFileNameW@4:PROC
_BSS	SEGMENT
?o@?1??mainCRTStartup@@9@9 DB 058H DUP (?)		; `mainCRTStartup'::`2'::o
?f@?1??mainCRTStartup@@9@9 DW 08000H DUP (?)		; `mainCRTStartup'::`2'::f
_BSS	ENDS
;	COMDAT ??_C@_19JDHDJODM@?$AAF?$AAA?$AAI?$AAL@
CONST	SEGMENT
??_C@_19JDHDJODM@?$AAF?$AAA?$AAI?$AAL@ DB 'F', 00H, 'A', 00H, 'I', 00H, 'L'
	DB	00H, 00H, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_15PMCGDJNJ@?$AAO?$AAK@
CONST	SEGMENT
??_C@_15PMCGDJNJ@?$AAO?$AAK@ DB 'O', 00H, 'K', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_17EGHIAIGL@?$AAN?$AAC?$AAM@
CONST	SEGMENT
??_C@_17EGHIAIGL@?$AAN?$AAC?$AAM@ DB 'N', 00H, 'C', 00H, 'M', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_04GMCJAHJC@TALB@
CONST	SEGMENT
??_C@_04GMCJAHJC@TALB@ DB 'TALB', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_04IPEPCGNC@TPE1@
CONST	SEGMENT
??_C@_04IPEPCGNC@TPE1@ DB 'TPE1', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_04JEJHKEED@TIT2@
CONST	SEGMENT
??_C@_04JEJHKEED@TIT2@ DB 'TIT2', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@PJKHLKFB@image?1jpeg@
CONST	SEGMENT
??_C@_0L@PJKHLKFB@image?1jpeg@ DB 'image/jpeg', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09NGJJJBGE@image?1png@
CONST	SEGMENT
??_C@_09NGJJJBGE@image?1png@ DB 'image/png', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_05MCBBJIDG@album@
CONST	SEGMENT
??_C@_05MCBBJIDG@album@ DB 'album', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_09MBFMNLN@musicName@
CONST	SEGMENT
??_C@_09MBFMNLN@musicName@ DB 'musicName', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06EEHJBIEA@music?3@
CONST	SEGMENT
??_C@_06EEHJBIEA@music?3@ DB 'music:', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BH@LNMJBFMK@163?5key?$CIDon?8t?5modify?$CJ?3@
CONST	SEGMENT
??_C@_0BH@LNMJBFMK@163?5key?$CIDon?8t?5modify?$CJ?3@ DB '163 key(Don''t m'
	DB	'odify):', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_06FOCAFPGH@artist@
CONST	SEGMENT
??_C@_06FOCAFPGH@artist@ DB 'artist', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_03PDOMKJON@bin@
CONST	SEGMENT
??_C@_03PDOMKJON@bin@ DB 'bin', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03EIHDBIJH@m4a@
CONST	SEGMENT
??_C@_03EIHDBIJH@m4a@ DB 'm4a', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03LHGNACFN@mp3@
CONST	SEGMENT
??_C@_03LHGNACFN@mp3@ DB 'mp3', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_04FJJKFLMH@flac@
CONST	SEGMENT
??_C@_04FJJKFLMH@flac@ DB 'flac', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_1BK@GPNIFMAA@?$AAO?$AAb?$AAj?$AAe?$AAc?$AAt?$AAL?$AAe?$AAn?$AAg?$AAt?$AAh@
CONST	SEGMENT
??_C@_1BK@GPNIFMAA@?$AAO?$AAb?$AAj?$AAe?$AAc?$AAt?$AAL?$AAe?$AAn?$AAg?$AAt?$AAh@ DB 'O'
	DB	00H, 'b', 00H, 'j', 00H, 'e', 00H, 'c', 00H, 't', 00H, 'L', 00H
	DB	'e', 00H, 'n', 00H, 'g', 00H, 't', 00H, 'h', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1BK@BCJKEJJO@?$AAC?$AAh?$AAa?$AAi?$AAn?$AAi?$AAn?$AAg?$AAM?$AAo?$AAd?$AAe@
CONST	SEGMENT
??_C@_1BK@BCJKEJJO@?$AAC?$AAh?$AAa?$AAi?$AAn?$AAi?$AAn?$AAg?$AAM?$AAo?$AAd?$AAe@ DB 'C'
	DB	00H, 'h', 00H, 'a', 00H, 'i', 00H, 'n', 00H, 'i', 00H, 'n', 00H
	DB	'g', 00H, 'M', 00H, 'o', 00H, 'd', 00H, 'e', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1CA@GGHMBPCI@?$AAC?$AAh?$AAa?$AAi?$AAn?$AAi?$AAn?$AAg?$AAM?$AAo?$AAd?$AAe?$AAE?$AAC?$AAB@
CONST	SEGMENT
??_C@_1CA@GGHMBPCI@?$AAC?$AAh?$AAa?$AAi?$AAn?$AAi?$AAn?$AAg?$AAM?$AAo?$AAd?$AAe?$AAE?$AAC?$AAB@ DB 'C'
	DB	00H, 'h', 00H, 'a', 00H, 'i', 00H, 'n', 00H, 'i', 00H, 'n', 00H
	DB	'g', 00H, 'M', 00H, 'o', 00H, 'd', 00H, 'e', 00H, 'E', 00H, 'C'
	DB	00H, 'B', 00H, 00H, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_17PJMHNJHG@?$AAA?$AAE?$AAS@
CONST	SEGMENT
??_C@_17PJMHNJHG@?$AAA?$AAE?$AAS@ DB 'A', 00H, 'E', 00H, 'S', 00H, 00H, 00H ; `string'
CONST	ENDS
; Function compile flags: /Ogspy
;	COMDAT _mainCRTStartup
_TEXT	SEGMENT
_mainCRTStartup PROC					; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 37
	push	esi
	push	edi
	mov	esi, OFFSET ?f@?1??mainCRTStartup@@9@9
	mov	DWORD PTR ?o@?1??mainCRTStartup@@9@9, 88 ; 00000058H
	mov	edi, OFFSET ??_C@_17EGHIAIGL@?$AAN?$AAC?$AAM@
	mov	DWORD PTR ?o@?1??mainCRTStartup@@9@9+12, OFFSET ?fil@?1??mainCRTStartup@@9@9
	push	OFFSET ?o@?1??mainCRTStartup@@9@9
	mov	DWORD PTR ?o@?1??mainCRTStartup@@9@9+28, esi
	mov	DWORD PTR ?o@?1??mainCRTStartup@@9@9+32, 32768 ; 00008000H
	mov	DWORD PTR ?o@?1??mainCRTStartup@@9@9+52, 530432 ; 00081800H
	mov	DWORD PTR ?o@?1??mainCRTStartup@@9@9+48, edi
	call	DWORD PTR __imp__GetOpenFileNameW@4
	push	0
	test	eax, eax
	jne	SHORT $LN2@mainCRTSta
$LN6@mainCRTSta:
	call	DWORD PTR __imp__ExitProcess@4
$LN2@mainCRTSta:
	push	esi
	call	_conv
	pop	ecx
	pop	ecx
	push	16					; 00000010H
	pop	ecx
	push	64					; 00000040H
	mov	esi, eax
	pop	eax
	test	esi, esi
	cmovne	ecx, eax
	mov	eax, OFFSET ??_C@_19JDHDJODM@?$AAF?$AAA?$AAI?$AAL@
	push	ecx
	push	edi
	mov	ecx, OFFSET ??_C@_15PMCGDJNJ@?$AAO?$AAK@
	cmove	ecx, eax
	push	ecx
	push	0
	call	DWORD PTR __imp__MessageBoxW@16
	push	2
	xor	ecx, ecx
	test	esi, esi
	pop	eax
	cmovne	eax, ecx
	push	eax
	jmp	SHORT $LN6@mainCRTSta
$LN5@mainCRTSta:
_mainCRTStartup ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _conv
_TEXT	SEGMENT
_au$1$ = -328						; size = 4
_kpl$ = -324						; size = 4
_ml$1$ = -324						; size = 4
_il$1$ = -324						; size = 4
tv558 = -324						; size = 4
_fl$ = -320						; size = 4
_p$1$ = -320						; size = 4
_f$ = -316						; size = 4
_mb$1$ = -312						; size = 4
_kp$ = -308						; size = 4
_kb$1$ = -304						; size = 4
_ok$1$ = -300						; size = 4
_tl$ = -296						; size = 4
_id3$1$ = -292						; size = 4
_t$ = -288						; size = 32
_bx$ = -256						; size = 256
_in$ = 8						; size = 4
_outarg$ = 12						; size = 4
_conv	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 36
	sub	esp, 328				; 00000148H
	push	ebx
	push	ebp
	push	esi
	push	edi
	push	8
	pop	ecx
	xor	eax, eax
	lea	edi, DWORD PTR _t$[esp+344]
	rep stosd
	xor	edx, edx
	lea	eax, DWORD PTR _fl$[esp+344]
	push	eax
	lea	eax, DWORD PTR _f$[esp+348]
	mov	DWORD PTR _f$[esp+348], edx
	push	eax
	push	DWORD PTR _in$[esp+348]
	mov	DWORD PTR _kb$1$[esp+356], edx
	mov	ebp, edx
	mov	DWORD PTR _kp$[esp+356], edx
	mov	DWORD PTR _mb$1$[esp+356], edx
	mov	DWORD PTR _id3$1$[esp+356], edx
	mov	DWORD PTR _fl$[esp+356], edx
	mov	DWORD PTR _tl$[esp+356], edx
	mov	DWORD PTR _ok$1$[esp+356], edx
	call	_rd
	mov	ebx, DWORD PTR _f$[esp+356]
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	$LN66@conv
	mov	esi, DWORD PTR _fl$[esp+344]
	cmp	esi, 32					; 00000020H
	jb	$LN66@conv
	mov	edx, OFFSET _M
	mov	eax, ebx
	sub	eax, edx
	push	8
	mov	DWORD PTR tv558[esp+348], eax
	pop	edi
$LL27@conv:
; Line 12
	mov	cl, BYTE PTR [eax+edx]
	dec	edi
	mov	al, BYTE PTR [edx]
	inc	edx
	cmp	cl, al
	jne	$LN66@conv
	mov	eax, DWORD PTR tv558[esp+344]
	test	edi, edi
	jne	SHORT $LL27@conv
; Line 36
	lea	eax, DWORD PTR [ebx+10]
	push	eax
	call	_r32
	mov	edi, eax
	pop	ecx
	test	edi, edi
	je	$LN66@conv
	lea	eax, DWORD PTR [edi+14]
	mov	DWORD PTR _p$1$[esp+344], eax
	cmp	eax, esi
	ja	$LN66@conv
	push	edi
	call	_A
	push	edi
	lea	ecx, DWORD PTR [ebx+14]
	mov	DWORD PTR _kb$1$[esp+352], eax
	push	ecx
	push	eax
	call	_cp
	mov	eax, DWORD PTR _kb$1$[esp+360]
	add	esp, 16					; 00000010H
	mov	edx, edi
	mov	ecx, eax
$LL32@conv:
; Line 12
	xor	BYTE PTR [ecx], 100			; 00000064H
	inc	ecx
	sub	edx, 1
	jne	SHORT $LL32@conv
; Line 36
	lea	ecx, DWORD PTR _kpl$[esp+344]
	push	ecx
	lea	ecx, DWORD PTR _kp$[esp+348]
	push	ecx
	push	OFFSET _CK
	push	edi
	push	eax
	call	_aes
	add	esp, 20					; 00000014H
	test	eax, eax
	je	$LN66@conv
	mov	eax, DWORD PTR _kpl$[esp+344]
	cmp	eax, 17					; 00000011H
	jbe	$LN66@conv
	lea	ecx, DWORD PTR _bx$[esp+344]
	add	eax, -17				; ffffffefH
	push	ecx
	push	eax
	mov	eax, DWORD PTR _kp$[esp+352]
	add	eax, 17					; 00000011H
	push	eax
	call	_box
	mov	edi, DWORD PTR _p$1$[esp+356]
	lea	eax, DWORD PTR [edi+ebx]
	push	eax
	call	_r32
	add	edi, 4
	mov	DWORD PTR _ml$1$[esp+360], eax
	mov	DWORD PTR _p$1$[esp+360], edi
	add	esp, 16					; 00000010H
	add	edi, eax
	cmp	edi, esi
	ja	$LN66@conv
	test	eax, eax
	je	SHORT $LN9@conv
	push	eax
	call	_A
	push	DWORD PTR _ml$1$[esp+348]
	mov	ecx, DWORD PTR _p$1$[esp+352]
	mov	edx, eax
	add	ecx, ebx
	mov	DWORD PTR _mb$1$[esp+352], edx
	push	ecx
	push	edx
	call	_cp
	lea	eax, DWORD PTR _t$[esp+360]
	push	eax
	push	DWORD PTR _ml$1$[esp+364]
	push	DWORD PTR _mb$1$[esp+368]
	call	_meta
	add	esp, 28					; 0000001cH
$LN9@conv:
	lea	eax, DWORD PTR [edi+13]
	cmp	eax, esi
	ja	$LN66@conv
	add	edi, 9
	lea	eax, DWORD PTR [edi+ebx]
	push	eax
	call	_r32
	mov	edx, eax
	add	edi, 4
	pop	ecx
	mov	DWORD PTR _il$1$[esp+344], edx
	lea	eax, DWORD PTR [edx+edi]
	cmp	eax, esi
	ja	$LN66@conv
	sub	esi, eax
	mov	DWORD PTR _t$[esp+372], edx
	lea	ecx, DWORD PTR [edi+ebx]
	push	esi
	mov	DWORD PTR _t$[esp+372], ecx
	call	_A
	mov	ecx, DWORD PTR _il$1$[esp+348]
	mov	ebp, eax
	add	ecx, edi
	mov	DWORD PTR _au$1$[esp+348], ebp
	push	esi
	add	ecx, ebx
	push	ecx
	push	ebp
	call	_cp
	add	esp, 16					; 00000010H
; Line 17
	test	esi, esi
	je	SHORT $LN37@conv
; Line 36
	xor	edx, edx
	mov	edi, ebp
	inc	edx
	mov	ebx, esi
	sub	edx, ebp
$LL38@conv:
; Line 17
	lea	eax, DWORD PTR [edx+edi]
	movzx	eax, al
	movzx	ecx, BYTE PTR _bx$[esp+eax+344]
	add	eax, ecx
	movzx	eax, al
	movzx	eax, BYTE PTR _bx$[esp+eax+344]
	add	eax, ecx
	movzx	eax, al
	mov	al, BYTE PTR _bx$[esp+eax+344]
	xor	BYTE PTR [edi], al
	inc	edi
	sub	ebx, 1
	jne	SHORT $LL38@conv
	mov	ebx, DWORD PTR _f$[esp+344]
$LN37@conv:
; Line 36
	push	esi
	push	ebp
	call	_ext
	cmp	DWORD PTR _outarg$[esp+348], 0
	mov	edi, eax
	pop	ecx
	pop	ecx
	je	SHORT $LN16@conv
	mov	ebp, DWORD PTR _outarg$[esp+340]
	jmp	SHORT $LN54@conv
$LN16@conv:
	push	edi
	push	DWORD PTR _in$[esp+344]
	call	_mkout
	mov	ebp, eax
	pop	ecx
	pop	ecx
	test	ebp, ebp
	je	SHORT $LN58@conv
$LN54@conv:
	cmp	BYTE PTR [edi], 109			; 0000006dH
	jne	SHORT $LN18@conv
	cmp	BYTE PTR [edi+1], 112			; 00000070H
	jne	SHORT $LN18@conv
	cmp	BYTE PTR [edi+2], 51			; 00000033H
	jne	SHORT $LN18@conv
	lea	eax, DWORD PTR _tl$[esp+344]
	push	eax
	lea	eax, DWORD PTR _t$[esp+348]
	push	eax
	call	_tag
	mov	DWORD PTR _id3$1$[esp+352], eax
	pop	ecx
	pop	ecx
	test	eax, eax
	je	SHORT $LN18@conv
	push	esi
	mov	esi, DWORD PTR _au$1$[esp+348]
	push	esi
	push	DWORD PTR _tl$[esp+352]
	push	eax
$LN90@conv:
	push	ebp
	call	_wr2
	add	esp, 20					; 00000014H
	mov	DWORD PTR _ok$1$[esp+344], eax
	jmp	SHORT $done$92
$LN18@conv:
	push	0
	push	0
	push	esi
	mov	esi, DWORD PTR _au$1$[esp+356]
	push	esi
; Line 12
	jmp	SHORT $LN90@conv
$LN66@conv:
; Line 36
	mov	esi, ebp
$done$92:
	cmp	DWORD PTR _outarg$[esp+340], 0
	jne	SHORT $LN14@conv
	jmp	SHORT $LN56@conv
$LN58@conv:
	mov	esi, DWORD PTR _au$1$[esp+344]
$LN56@conv:
	push	ebp
	call	_F
	pop	ecx
$LN14@conv:
	push	DWORD PTR _id3$1$[esp+344]
	call	_F
	push	DWORD PTR _t$[esp+348]
	call	_F
	push	DWORD PTR _t$[esp+356]
	call	_F
	push	DWORD PTR _t$[esp+364]
	call	_F
	push	DWORD PTR _mb$1$[esp+360]
	call	_F
	push	esi
	call	_F
; Line 10
	mov	eax, DWORD PTR _kp$[esp+368]
; Line 36
	add	esp, 24					; 00000018H
; Line 10
	mov	esi, DWORD PTR __imp__HeapFree@12
	mov	edi, DWORD PTR __imp__GetProcessHeap@0
	test	eax, eax
	je	SHORT $LN21@conv
	push	eax
	push	0
	call	edi
	push	eax
	call	esi
$LN21@conv:
; Line 36
	push	DWORD PTR _kb$1$[esp+344]
	call	_F
	pop	ecx
; Line 10
	test	ebx, ebx
	je	SHORT $LN24@conv
	push	ebx
	push	0
	call	edi
	push	eax
	call	esi
$LN24@conv:
; Line 36
	mov	eax, DWORD PTR _ok$1$[esp+344]
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	add	esp, 328				; 00000148H
	ret	0
_conv	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _tag
_TEXT	SEGMENT
_t$ = 8							; size = 4
_tn$ = 12						; size = 4
_tag	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 35
	push	ebx
	mov	ebx, DWORD PTR _t$[esp]
	push	esi
	mov	ecx, DWORD PTR [ebx+12]
	add	ecx, DWORD PTR [ebx+16]
	add	ecx, DWORD PTR [ebx+20]
	mov	eax, DWORD PTR [ebx+28]
	lea	eax, DWORD PTR [eax+ecx*2]
	add	eax, 138				; 0000008aH
	push	eax
	call	_A
	mov	esi, eax
	pop	ecx
	test	esi, esi
	je	$LN1@tag
$LN2@tag:
	push	edi
	mov	DWORD PTR [esi], 53691465		; 03334449H
	lea	eax, DWORD PTR [esi+10]
	mov	WORD PTR [esi+4], 0
	push	DWORD PTR [ebx+12]
	push	DWORD PTR [ebx]
	push	OFFSET ??_C@_04JEJHKEED@TIT2@
	push	eax
	call	_ft
	push	DWORD PTR [ebx+16]
	push	DWORD PTR [ebx+4]
	lea	edi, DWORD PTR [eax+10]
	lea	ecx, DWORD PTR [esi+edi]
	push	OFFSET ??_C@_04IPEPCGNC@TPE1@
	push	ecx
	call	_ft
	push	DWORD PTR [ebx+20]
	add	edi, eax
	push	DWORD PTR [ebx+8]
	push	OFFSET ??_C@_04GMCJAHJC@TALB@
	lea	eax, DWORD PTR [esi+edi]
	push	eax
	call	_ft
	push	DWORD PTR [ebx+28]
	add	edi, eax
	push	DWORD PTR [ebx+24]
	lea	eax, DWORD PTR [esi+edi]
	push	eax
	call	_fa
	add	edi, eax
	add	esp, 60					; 0000003cH
	cmp	edi, 10					; 0000000aH
	jne	SHORT $LN3@tag
	push	esi
	call	_F
	pop	ecx
	xor	eax, eax
	jmp	SHORT $LN9@tag
$LN3@tag:
	lea	ecx, DWORD PTR [edi-10]
; Line 11
	mov	eax, ecx
	shr	eax, 21					; 00000015H
	and	al, 127					; 0000007fH
	mov	BYTE PTR [esi+6], al
	mov	eax, ecx
	shr	eax, 14					; 0000000eH
	and	al, 127					; 0000007fH
	mov	BYTE PTR [esi+7], al
	mov	eax, ecx
	shr	eax, 7
	and	al, 127					; 0000007fH
	and	cl, 127					; 0000007fH
	mov	BYTE PTR [esi+8], al
; Line 35
	mov	eax, DWORD PTR _tn$[esp+8]
; Line 11
	mov	BYTE PTR [esi+9], cl
; Line 35
	mov	DWORD PTR [eax], edi
	mov	eax, esi
$LN9@tag:
	pop	edi
$LN1@tag:
	pop	esi
	pop	ebx
	ret	0
_tag	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _fa
_TEXT	SEGMENT
tv511 = -4						; size = 4
_o$ = 8							; size = 4
_im$ = 12						; size = 4
_n$ = 16						; size = 4
tv504 = 16						; size = 4
_fa	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 34
	push	ecx
	push	ebx
	mov	ebx, DWORD PTR _im$[esp+4]
	push	ebp
	mov	ebp, DWORD PTR _n$[esp+8]
	push	esi
	cmp	ebp, 4
	jbe	SHORT $LN10@fa
	cmp	BYTE PTR [ebx], 137			; 00000089H
	jne	SHORT $LN10@fa
	cmp	BYTE PTR [ebx+1], 80			; 00000050H
	jne	SHORT $LN10@fa
	mov	al, BYTE PTR ??_C@_09NGJJJBGE@image?1png@
	mov	ecx, OFFSET ??_C@_09NGJJJBGE@image?1png@
	mov	edx, ecx
	xor	esi, esi
	mov	DWORD PTR tv504[esp+12], edx
	jmp	SHORT $LN29@fa
$LN10@fa:
	mov	al, BYTE PTR ??_C@_0L@PJKHLKFB@image?1jpeg@
	mov	ecx, OFFSET ??_C@_0L@PJKHLKFB@image?1jpeg@
	mov	edx, ecx
	mov	DWORD PTR tv504[esp+12], edx
	test	ebx, ebx
	je	$LN8@fa
	xor	esi, esi
	test	ebp, ebp
	je	$LN8@fa
$LN29@fa:
	test	al, al
	je	SHORT $LN3@fa
$LL2@fa:
	inc	esi
	cmp	BYTE PTR [edx+esi], 0
	jne	SHORT $LL2@fa
$LN3@fa:
	lea	edx, DWORD PTR [ebp+4]
	add	edx, esi
	push	edi
	mov	edi, DWORD PTR _o$[esp+16]
; Line 11
	mov	eax, edx
	shr	eax, 24					; 00000018H
	mov	BYTE PTR [edi+4], al
	mov	eax, edx
	shr	eax, 16					; 00000010H
	mov	BYTE PTR [edi+5], al
	mov	eax, edx
	shr	eax, 8
	mov	BYTE PTR [edi+7], dl
; Line 34
	xor	edx, edx
	mov	DWORD PTR [edi], 1128878145		; 43495041H
; Line 11
	mov	BYTE PTR [edi+6], al
; Line 34
	mov	WORD PTR [edi+8], 0
	mov	BYTE PTR [edi+10], 3
	test	esi, esi
	je	SHORT $LN5@fa
	cmp	esi, 16					; 00000010H
	jb	SHORT $LN27@fa
	lea	eax, DWORD PTR [edi+11]
	mov	DWORD PTR tv511[esp+20], eax
	lea	eax, DWORD PTR [ecx-1]
	add	eax, esi
	cmp	DWORD PTR tv511[esp+20], eax
	ja	SHORT $LN20@fa
	lea	eax, DWORD PTR [edi+10]
	add	eax, esi
	cmp	eax, ecx
	jae	SHORT $LN27@fa
$LN20@fa:
	push	esi
	push	ecx
	lea	eax, DWORD PTR [edi+11]
	push	eax
	call	_cp
	add	esp, 12					; 0000000cH
	jmp	SHORT $LN5@fa
$LN27@fa:
	mov	ebx, DWORD PTR tv504[esp+16]
	lea	ecx, DWORD PTR [edi+11]
	add	ecx, edx
$LL18@fa:
	mov	al, BYTE PTR [ebx+edx]
	inc	edx
	mov	BYTE PTR [ecx], al
	inc	ecx
	cmp	edx, esi
	jb	SHORT $LL18@fa
	mov	ebx, DWORD PTR _im$[esp+16]
$LN5@fa:
	push	ebp
	lea	eax, DWORD PTR [edi+14]
	mov	WORD PTR [esi+edi+11], 768		; 00000300H
	add	eax, esi
	mov	BYTE PTR [esi+edi+13], 0
	push	ebx
	push	eax
	call	_cp
	add	esp, 12					; 0000000cH
	lea	eax, DWORD PTR [ebp+14]
	add	eax, esi
	pop	edi
	jmp	SHORT $LN1@fa
$LN8@fa:
	xor	eax, eax
$LN1@fa:
	pop	esi
	pop	ebp
	pop	ebx
	pop	ecx
	ret	0
_fa	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _ft
_TEXT	SEGMENT
_o$ = 8							; size = 4
_id$ = 12						; size = 4
_s$ = 16						; size = 4
_n$ = 20						; size = 4
_ft	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 33
	push	ebp
	mov	ebp, esp
	cmp	DWORD PTR _s$[ebp], 0
	je	SHORT $LN3@ft
	cmp	DWORD PTR _n$[ebp], 0
	je	SHORT $LN3@ft
	push	esi
	push	edi
	push	DWORD PTR _n$[ebp]
	push	DWORD PTR _s$[ebp]
	call	_u16n
	mov	esi, DWORD PTR _o$[ebp]
	mov	edi, eax
	mov	edx, DWORD PTR _id$[ebp]
	push	DWORD PTR _n$[ebp]
	push	DWORD PTR _s$[ebp]
	mov	cl, BYTE PTR [edx]
	mov	BYTE PTR [esi], cl
	mov	cl, BYTE PTR [edx+1]
	mov	BYTE PTR [esi+1], cl
	mov	cl, BYTE PTR [edx+2]
	mov	BYTE PTR [esi+2], cl
	mov	cl, BYTE PTR [edx+3]
	mov	BYTE PTR [esi+3], cl
	lea	ecx, DWORD PTR [edi+3]
; Line 11
	mov	eax, ecx
	mov	BYTE PTR [esi+7], cl
	shr	eax, 24					; 00000018H
	mov	BYTE PTR [esi+4], al
	mov	eax, ecx
	shr	eax, 16					; 00000010H
	mov	BYTE PTR [esi+5], al
	mov	eax, ecx
	shr	eax, 8
	mov	BYTE PTR [esi+6], al
; Line 33
	lea	eax, DWORD PTR [esi+13]
	push	eax
	mov	DWORD PTR [esi+8], -16711680		; ff010000H
	mov	BYTE PTR [esi+12], 254			; 000000feH
	call	_w16
	add	esp, 20					; 00000014H
	lea	eax, DWORD PTR [edi+13]
	pop	edi
	pop	esi
	pop	ebp
	ret	0
$LN3@ft:
	xor	eax, eax
	pop	ebp
	ret	0
_ft	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _w16
_TEXT	SEGMENT
_o$ = 8							; size = 4
_s$ = 12						; size = 4
_n$ = 16						; size = 4
_w16	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 32
	push	ebx
	mov	ebx, DWORD PTR _n$[esp]
	xor	edx, edx
	push	esi
	mov	esi, edx
	test	ebx, ebx
	je	SHORT $LN3@w16
	push	ebp
	mov	ebp, DWORD PTR _s$[esp+8]
	push	edi
	xor	edi, edi
	inc	edi
$LL2@w16:
	mov	ah, BYTE PTR [edx+ebp]
	inc	edx
	mov	al, ah
	inc	edi
	and	al, 224					; 000000e0H
	cmp	al, 192					; 000000c0H
	jne	SHORT $LN4@w16
	cmp	edx, ebx
	jae	SHORT $LN4@w16
	movzx	ecx, BYTE PTR [edx+ebp]
	movzx	eax, ah
	and	ecx, 63					; 0000003fH
	and	eax, 31					; 0000001fH
	shl	eax, 6
	or	ecx, eax
	inc	edx
	inc	edi
	jmp	SHORT $LN7@w16
$LN4@w16:
	mov	al, ah
	and	al, 240					; 000000f0H
	cmp	al, 224					; 000000e0H
	jne	SHORT $LN12@w16
	cmp	edi, ebx
	jae	SHORT $LN12@w16
	movzx	ecx, BYTE PTR [edx+ebp]
	movzx	eax, ah
	and	ecx, 63					; 0000003fH
	and	eax, 15					; 0000000fH
	shl	eax, 6
	or	ecx, eax
	movzx	eax, BYTE PTR [edx+ebp+1]
	shl	ecx, 6
	and	eax, 63					; 0000003fH
	or	ecx, eax
	add	edx, 2
	add	edi, 2
	jmp	SHORT $LN7@w16
$LN12@w16:
	movzx	ecx, ah
$LN7@w16:
	mov	eax, DWORD PTR _o$[esp+12]
	mov	BYTE PTR [esi+eax], cl
	shr	ecx, 8
	mov	BYTE PTR [esi+eax+1], cl
	add	esi, 2
	cmp	edx, ebx
	jb	SHORT $LL2@w16
	pop	edi
	pop	ebp
$LN3@w16:
	mov	eax, esi
	pop	esi
	pop	ebx
	ret	0
_w16	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _u16n
_TEXT	SEGMENT
_s$ = 8							; size = 4
_n$ = 12						; size = 4
_u16n	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 31
	push	esi
	mov	esi, DWORD PTR _n$[esp]
	xor	ecx, ecx
	push	edi
	mov	edi, ecx
	test	esi, esi
	je	SHORT $LN3@u16n
	push	ebx
	xor	edx, edx
	push	ebp
	mov	ebp, DWORD PTR _s$[esp+12]
	inc	edx
$LL2@u16n:
	mov	bl, BYTE PTR [ecx+ebp]
	inc	ecx
	mov	al, bl
	inc	edx
	and	al, 224					; 000000e0H
	cmp	al, 192					; 000000c0H
	jne	SHORT $LN4@u16n
	cmp	ecx, esi
	jae	SHORT $LN4@u16n
	inc	ecx
	inc	edx
	jmp	SHORT $LN6@u16n
$LN4@u16n:
	and	bl, 240					; 000000f0H
	cmp	bl, 224					; 000000e0H
	jne	SHORT $LN6@u16n
	cmp	edx, esi
	jae	SHORT $LN6@u16n
	add	ecx, 2
	add	edx, 2
$LN6@u16n:
	add	edi, 2
	cmp	ecx, esi
	jb	SHORT $LL2@u16n
	pop	ebp
	pop	ebx
$LN3@u16n:
	mov	eax, edi
	pop	edi
	pop	esi
	ret	0
_u16n	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _meta
_TEXT	SEGMENT
_p$ = -36						; size = 4
_dn$ = -32						; size = 4
_pn2$ = -28						; size = 4
_pre$ = -24						; size = 23
_m$ = 8							; size = 4
_mn$ = 12						; size = 4
_d$1$ = 12						; size = 4
_t$ = 16						; size = 4
_meta	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 30
	sub	esp, 36					; 00000024H
	push	esi
	push	edi
	push	5
	pop	ecx
	mov	esi, OFFSET ??_C@_0BH@LNMJBFMK@163?5key?$CIDon?8t?5modify?$CJ?3@
	mov	DWORD PTR _dn$[esp+44], 0
	lea	edi, DWORD PTR _pre$[esp+44]
	mov	DWORD PTR _pn2$[esp+44], 0
	rep movsd
	movsw
	movsb
	mov	esi, DWORD PTR _mn$[esp+40]
	xor	edi, edi
	mov	DWORD PTR _p$[esp+44], edi
	cmp	esi, 22					; 00000016H
	jbe	$LN1@meta
	push	ebx
	mov	ebx, DWORD PTR _m$[esp+44]
	mov	ecx, esi
	mov	eax, ebx
$LL8@meta:
; Line 12
	xor	BYTE PTR [eax], 99			; 00000063H
	inc	eax
	sub	ecx, 1
	jne	SHORT $LL8@meta
; Line 30
	lea	eax, DWORD PTR _pre$[esp+48]
	push	eax
	push	esi
	push	ebx
	call	_st
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	$LN28@meta
	push	ebp
	lea	eax, DWORD PTR _dn$[esp+52]
	push	eax
	lea	eax, DWORD PTR [esi-22]
	push	eax
	lea	eax, DWORD PTR [ebx+22]
	push	eax
	call	_b64
	mov	ebp, eax
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _d$1$[esp+48], ebp
	test	ebp, ebp
	je	$LN4@meta
	lea	eax, DWORD PTR _pn2$[esp+52]
	push	eax
	lea	eax, DWORD PTR _p$[esp+56]
	push	eax
	push	OFFSET _MK
	push	DWORD PTR _dn$[esp+64]
	push	ebp
	call	_aes
	add	esp, 20					; 00000014H
	test	eax, eax
	je	SHORT $LN19@meta
	mov	ebx, DWORD PTR _pn2$[esp+52]
	cmp	ebx, 6
	jbe	SHORT $LN19@meta
	mov	edi, DWORD PTR _p$[esp+52]
	mov	ebp, edi
	push	OFFSET ??_C@_06EEHJBIEA@music?3@
	push	ebx
	push	edi
	call	_st
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	SHORT $LN5@meta
	add	ebp, 6
	sub	ebx, 6
$LN5@meta:
	mov	esi, DWORD PTR _t$[esp+48]
	lea	eax, DWORD PTR [esi+12]
	push	eax
	push	OFFSET ??_C@_09MBFMNLN@musicName@
	push	ebx
	push	ebp
	call	_fld
	mov	DWORD PTR [esi], eax
	lea	eax, DWORD PTR [esi+20]
	push	eax
	push	OFFSET ??_C@_05MCBBJIDG@album@
	push	ebx
	push	ebp
	call	_fld
	mov	DWORD PTR [esi+8], eax
	lea	eax, DWORD PTR [esi+16]
	push	eax
	push	ebx
	push	ebp
	call	_art
	mov	ebp, DWORD PTR _d$1$[esp+92]
	add	esp, 44					; 0000002cH
	mov	DWORD PTR [esi+4], eax
	jmp	SHORT $LN4@meta
$LN19@meta:
	mov	edi, DWORD PTR _p$[esp+52]
$LN4@meta:
; Line 10
	test	edi, edi
	je	SHORT $LN12@meta
	push	edi
	push	0
	call	DWORD PTR __imp__GetProcessHeap@0
	push	eax
	call	DWORD PTR __imp__HeapFree@12
$LN12@meta:
; Line 30
	push	ebp
	call	_F
	pop	ecx
	pop	ebp
$LN28@meta:
	pop	ebx
$LN1@meta:
	pop	edi
	pop	esi
	add	esp, 36					; 00000024H
	ret	0
_meta	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _b64
_TEXT	SEGMENT
_a$1$ = -12						; size = 4
_b$1$ = -8						; size = 4
tv418 = -4						; size = 4
_i$ = 8							; size = 4
_n$ = 12						; size = 4
_on$ = 16						; size = 4
_b64	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 29
	mov	eax, DWORD PTR _n$[esp-4]
	sub	esp, 12					; 0000000cH
	shr	eax, 2
	inc	eax
	imul	eax, eax, 3
	push	ebp
	push	esi
	push	eax
	call	_A
	mov	ebp, eax
	xor	esi, esi
	pop	ecx
	test	ebp, ebp
	je	$LN1@b64
$LN5@b64:
	cmp	DWORD PTR _n$[esp+16], 3
	jbe	$LN20@b64
	mov	eax, DWORD PTR _i$[esp+16]
	xor	ecx, ecx
	inc	ecx
	push	edi
	sub	ecx, eax
	lea	edi, DWORD PTR [eax+2]
	mov	DWORD PTR tv418[esp+24], ecx
	push	ebx
$LL4@b64:
	movzx	eax, BYTE PTR [edi-2]
	push	eax
	call	_b64v
	movzx	ecx, BYTE PTR [edi-1]
	push	ecx
	mov	DWORD PTR _a$1$[esp+36], eax
	call	_b64v
	mov	DWORD PTR _b$1$[esp+36], eax
	mov	al, BYTE PTR [edi]
	pop	ecx
	pop	ecx
	cmp	al, 61					; 0000003dH
	jne	SHORT $LN11@b64
	push	-2					; fffffffeH
	pop	ebx
	jmp	SHORT $LN12@b64
$LN11@b64:
	push	eax
	call	_b64v
	pop	ecx
	mov	ebx, eax
$LN12@b64:
	mov	al, BYTE PTR [edi+1]
	cmp	al, 61					; 0000003dH
	jne	SHORT $LN13@b64
	push	-2					; fffffffeH
	pop	ecx
	jmp	SHORT $LN14@b64
$LN13@b64:
	push	eax
	call	_b64v
	pop	ecx
	mov	ecx, eax
$LN14@b64:
	cmp	DWORD PTR _a$1$[esp+28], 0
	jl	SHORT $LN33@b64
	mov	edx, DWORD PTR _b$1$[esp+28]
	test	edx, edx
	js	SHORT $LN33@b64
	cmp	ebx, -2					; fffffffeH
	jl	SHORT $LN33@b64
	cmp	ecx, -2					; fffffffeH
	jl	SHORT $LN33@b64
	shl	BYTE PTR _a$1$[esp+28], 2
	mov	eax, edx
	sar	eax, 4
	or	al, BYTE PTR _a$1$[esp+28]
	mov	BYTE PTR [esi+ebp], al
	inc	esi
	test	ebx, ebx
	js	SHORT $LN8@b64
	mov	eax, ebx
	shl	dl, 4
	sar	eax, 2
	or	al, dl
	mov	BYTE PTR [esi+ebp], al
	inc	esi
$LN8@b64:
	test	ecx, ecx
	js	SHORT $LN2@b64
	test	ebx, ebx
	js	SHORT $LN2@b64
	shl	bl, 6
	or	bl, cl
	mov	BYTE PTR [esi+ebp], bl
	inc	esi
$LN2@b64:
	mov	eax, DWORD PTR tv418[esp+28]
	add	edi, 4
	add	eax, edi
	cmp	eax, DWORD PTR _n$[esp+24]
	jb	$LL4@b64
$LN33@b64:
	pop	ebx
	pop	edi
$LN20@b64:
	mov	eax, DWORD PTR _on$[esp+16]
	mov	DWORD PTR [eax], esi
	mov	eax, ebp
$LN1@b64:
	pop	esi
	pop	ebp
	add	esp, 12					; 0000000cH
	ret	0
_b64	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _b64v
_TEXT	SEGMENT
_c$ = 8							; size = 1
_b64v	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 28
	mov	cl, BYTE PTR _c$[esp-4]
	lea	eax, DWORD PTR [ecx-65]
	cmp	al, 25					; 00000019H
	ja	SHORT $LN3@b64v
	movzx	eax, cl
	sub	eax, 65					; 00000041H
	ret	0
$LN3@b64v:
	lea	eax, DWORD PTR [ecx-97]
	cmp	al, 25					; 00000019H
	ja	SHORT $LN4@b64v
	movzx	eax, cl
	sub	eax, 71					; 00000047H
	ret	0
$LN4@b64v:
	lea	eax, DWORD PTR [ecx-48]
	cmp	al, 9
	ja	SHORT $LN5@b64v
	movzx	eax, cl
	add	eax, 4
	ret	0
$LN5@b64v:
	or	eax, -1
	cmp	cl, 47					; 0000002fH
	push	63					; 0000003fH
	pop	edx
	cmove	eax, edx
	cmp	cl, 43					; 0000002bH
	push	62					; 0000003eH
	pop	edx
	cmove	eax, edx
	ret	0
_b64v	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _art
_TEXT	SEGMENT
_sn$ = -8						; size = 4
_s$1$ = -4						; size = 4
_j$ = 8							; size = 4
_dep$1$ = 8						; size = 4
_n$ = 12						; size = 4
_cnt$1$ = 12						; size = 4
_on$ = 16						; size = 4
_art	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 27
	push	ecx
	push	ecx
	mov	ecx, DWORD PTR _j$[esp+4]
	push	ebx
	push	ebp
	mov	ebp, DWORD PTR _n$[esp+12]
	push	esi
	push	edi
	add	ebp, ecx
	push	OFFSET ??_C@_06FOCAFPGH@artist@
	push	ebp
	push	ecx
	call	_key
	xor	edi, edi
	mov	esi, eax
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _dep$1$[esp+20], edi
	mov	DWORD PTR _cnt$1$[esp+20], edi
	test	esi, esi
	je	$LN38@art
	push	256					; 00000100H
	call	_A
	mov	ebx, eax
	pop	ecx
	test	ebx, ebx
	je	$LN38@art
	cmp	esi, ebp
	jae	$LN37@art
$LL4@art:
	mov	al, BYTE PTR [esi]
	cmp	al, 91					; 0000005bH
	jne	SHORT $LN11@art
	inc	DWORD PTR _dep$1$[esp+20]
	jmp	$LN2@art
$LN11@art:
	cmp	al, 93					; 0000005dH
	jne	SHORT $LN13@art
	mov	eax, DWORD PTR _dep$1$[esp+20]
	test	eax, eax
	je	$LN26@art
	sub	eax, 1
	mov	DWORD PTR _dep$1$[esp+20], eax
	je	$LN26@art
	jmp	$LN2@art
$LN13@art:
	cmp	al, 34					; 00000022H
	jne	$LN2@art
	cmp	DWORD PTR _dep$1$[esp+20], 2
	jb	$LN2@art
	lea	eax, DWORD PTR _sn$[esp+24]
	push	eax
	push	ebp
	push	esi
	call	_jstr
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _s$1$[esp+24], eax
	test	eax, eax
	je	SHORT $LN18@art
	mov	edx, DWORD PTR _sn$[esp+24]
	test	edx, edx
	je	SHORT $LN18@art
	lea	ecx, DWORD PTR [edx+2]
	add	ecx, edi
	cmp	ecx, 256				; 00000100H
	ja	SHORT $LN18@art
	mov	ecx, DWORD PTR _cnt$1$[esp+20]
	mov	eax, ecx
	inc	ecx
	mov	DWORD PTR _cnt$1$[esp+20], ecx
	test	eax, eax
	je	SHORT $LN19@art
	mov	BYTE PTR [ebx+edi], 47			; 0000002fH
	inc	edi
$LN19@art:
	push	edx
	push	DWORD PTR _s$1$[esp+28]
	lea	eax, DWORD PTR [ebx+edi]
	push	eax
	call	_cp
	mov	eax, DWORD PTR _s$1$[esp+36]
	add	esp, 12					; 0000000cH
	add	edi, DWORD PTR _sn$[esp+24]
$LN18@art:
	push	eax
	call	_F
	pop	ecx
$LL5@art:
	cmp	BYTE PTR [esi], 34			; 00000022H
	je	SHORT $LN6@art
	inc	esi
	cmp	esi, ebp
	jb	SHORT $LL5@art
$LN6@art:
	cmp	esi, ebp
	lea	eax, DWORD PTR [esi+1]
	cmovae	eax, esi
	mov	esi, eax
	jmp	SHORT $LN59@art
$LL7@art:
	cmp	BYTE PTR [esi], 34			; 00000022H
	je	SHORT $LN2@art
	inc	esi
$LN59@art:
	cmp	esi, ebp
	jb	SHORT $LL7@art
$LN2@art:
	inc	esi
	cmp	esi, ebp
	jb	$LL4@art
$LN26@art:
	test	edi, edi
	je	SHORT $LN37@art
	mov	eax, DWORD PTR _on$[esp+20]
	mov	BYTE PTR [ebx+edi], 0
	mov	DWORD PTR [eax], edi
	mov	eax, ebx
	jmp	SHORT $LN1@art
$LN37@art:
	push	ebx
	call	_F
	pop	ecx
$LN38@art:
	xor	eax, eax
$LN1@art:
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	pop	ecx
	pop	ecx
	ret	0
_art	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _fld
_TEXT	SEGMENT
_j$ = 8							; size = 4
_n$ = 12						; size = 4
_k$ = 16						; size = 4
_on$ = 20						; size = 4
_fld	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 26
	mov	ecx, DWORD PTR _j$[esp-4]
	push	esi
	mov	esi, DWORD PTR _n$[esp]
	push	DWORD PTR _k$[esp]
	add	esi, ecx
	push	esi
	push	ecx
	call	_key
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN17@fld
	pop	esi
	ret	0
$LL2@fld:
	mov	cl, BYTE PTR [eax]
	cmp	cl, 32					; 00000020H
	je	SHORT $LN5@fld
	cmp	cl, 9
	je	SHORT $LN5@fld
	cmp	cl, 10					; 0000000aH
	je	SHORT $LN5@fld
	cmp	cl, 13					; 0000000dH
	jne	SHORT $LN11@fld
$LN5@fld:
	inc	eax
$LN17@fld:
	cmp	eax, esi
	jb	SHORT $LL2@fld
$LN11@fld:
	push	DWORD PTR _on$[esp]
	push	esi
	push	eax
	call	_jstr
	add	esp, 12					; 0000000cH
	pop	esi
	ret	0
_fld	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _key
_TEXT	SEGMENT
_p$ = 8							; size = 4
_e$ = 12						; size = 4
_k$ = 16						; size = 4
_key	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 25
	push	ebx
	mov	ebx, DWORD PTR _k$[esp]
	xor	edx, edx
	push	esi
	push	edi
	cmp	BYTE PTR [ebx], dl
	je	SHORT $LN3@key
$LL2@key:
	inc	edx
	cmp	BYTE PTR [ebx+edx], 0
	jne	SHORT $LL2@key
$LN3@key:
	mov	ecx, DWORD PTR _p$[esp+8]
	mov	edi, DWORD PTR _e$[esp+8]
	jmp	SHORT $LN48@key
$LL6@key:
	cmp	BYTE PTR [ecx], 34			; 00000022H
	jne	SHORT $LN4@key
	xor	esi, esi
	test	edx, edx
	je	SHORT $LN8@key
$LL9@key:
	mov	al, BYTE PTR [ecx+esi+1]
	cmp	al, BYTE PTR [ebx+esi]
	jne	SHORT $LN4@key
	inc	esi
	cmp	esi, edx
	jb	SHORT $LL9@key
$LN8@key:
	cmp	esi, edx
	jne	SHORT $LN4@key
	lea	eax, DWORD PTR [edx+ecx]
	cmp	BYTE PTR [eax+1], 34			; 00000022H
	jne	SHORT $LN4@key
	lea	ecx, DWORD PTR [eax+2]
	cmp	ecx, edi
	jae	SHORT $LN4@key
$LL10@key:
	mov	al, BYTE PTR [ecx]
	cmp	al, 32					; 00000020H
	je	SHORT $LN14@key
	cmp	al, 9
	je	SHORT $LN14@key
	cmp	al, 10					; 0000000aH
	je	SHORT $LN14@key
	cmp	al, 13					; 0000000dH
	jne	SHORT $LN11@key
$LN14@key:
	inc	ecx
	cmp	ecx, edi
	jb	SHORT $LL10@key
$LN11@key:
	cmp	ecx, edi
	jae	SHORT $LN4@key
	cmp	BYTE PTR [ecx], 58			; 0000003aH
	je	SHORT $LN21@key
$LN4@key:
	inc	ecx
$LN48@key:
	lea	eax, DWORD PTR [ecx+2]
	add	eax, edx
	cmp	eax, edi
	jb	SHORT $LL6@key
	xor	eax, eax
$LN1@key:
	pop	edi
	pop	esi
	pop	ebx
	ret	0
$LN21@key:
	lea	eax, DWORD PTR [ecx+1]
	jmp	SHORT $LN1@key
_key	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _jstr
_TEXT	SEGMENT
_o$1$ = -20						; size = 4
_z$ = -16						; size = 4
_d$1$ = -12						; size = 4
_b$1$ = -8						; size = 4
_c$1$ = -4						; size = 4
_p$ = 8							; size = 4
$T1 = 8							; size = 1
_e$ = 12						; size = 4
_n$ = 16						; size = 4
_jstr	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 24
	sub	esp, 20					; 00000014H
	push	esi
	mov	esi, DWORD PTR _p$[esp+20]
	push	edi
	xor	edi, edi
	mov	DWORD PTR _z$[esp+28], edi
	cmp	esi, DWORD PTR _e$[esp+24]
	jae	$LN5@jstr
	cmp	BYTE PTR [esi], 34			; 00000022H
	jne	$LN5@jstr
	mov	eax, DWORD PTR _e$[esp+24]
	inc	esi
	sub	eax, esi
	inc	eax
	push	eax
	call	_A
	pop	ecx
	mov	ecx, eax
	mov	DWORD PTR _o$1$[esp+28], ecx
	test	ecx, ecx
	je	$LN5@jstr
	cmp	esi, DWORD PTR _e$[esp+24]
	jae	$LN21@jstr
	push	ebx
	push	ebp
	lea	ebx, DWORD PTR [esi+4]
	lea	ebp, DWORD PTR [esi+1]
$LL2@jstr:
	mov	al, BYTE PTR [esi]
	cmp	al, 34					; 00000022H
	je	$LN41@jstr
	cmp	al, 92					; 0000005cH
	jne	$LN7@jstr
	cmp	ebp, DWORD PTR _e$[esp+32]
	jae	$LN7@jstr
	inc	esi
	inc	ebp
	inc	ebx
	mov	al, BYTE PTR [esi]
	mov	BYTE PTR $T1[esp+32], al
	cmp	al, 117					; 00000075H
	jne	$LN10@jstr
	cmp	ebx, DWORD PTR _e$[esp+32]
	jae	$LN12@jstr
	movzx	eax, BYTE PTR [ebp]
	push	eax
	call	_hv
	movzx	ecx, BYTE PTR [esi+2]
	mov	edx, eax
	push	ecx
	call	_hv
	movzx	ecx, BYTE PTR [esi+3]
	push	ecx
	mov	DWORD PTR _b$1$[esp+48], eax
	call	_hv
	movzx	ecx, BYTE PTR [ebx]
	push	ecx
	mov	DWORD PTR _c$1$[esp+52], eax
	call	_hv
	add	esp, 16					; 00000010H
	mov	DWORD PTR _d$1$[esp+36], eax
	test	edx, edx
	js	SHORT $LN25@jstr
	mov	eax, DWORD PTR _b$1$[esp+36]
	test	eax, eax
	js	SHORT $LN25@jstr
	mov	ecx, DWORD PTR _c$1$[esp+36]
	test	ecx, ecx
	js	SHORT $LN25@jstr
	cmp	DWORD PTR _d$1$[esp+36], 0
	jl	SHORT $LN25@jstr
	shl	edx, 4
	or	edx, eax
	lea	eax, DWORD PTR _z$[esp+36]
	shl	edx, 4
	or	edx, ecx
	shl	edx, 4
	or	edx, DWORD PTR _d$1$[esp+36]
	push	edx
	push	eax
	push	DWORD PTR _o$1$[esp+44]
	call	_pu
	mov	edi, DWORD PTR _z$[esp+48]
	add	esp, 12					; 0000000cH
	mov	ecx, DWORD PTR _o$1$[esp+36]
	add	esi, 5
	add	ebp, 5
	add	ebx, 5
	jmp	SHORT $LN8@jstr
$LN10@jstr:
	cmp	al, 110					; 0000006eH
	jne	SHORT $LN14@jstr
	add	al, 156					; 0000009cH
	jmp	SHORT $LN13@jstr
$LN14@jstr:
	cmp	al, 116					; 00000074H
	jne	SHORT $LN12@jstr
	add	al, 149					; 00000095H
	jmp	SHORT $LN13@jstr
$LN25@jstr:
	mov	ecx, DWORD PTR _o$1$[esp+36]
$LN12@jstr:
	mov	al, BYTE PTR $T1[esp+32]
	inc	esi
	inc	ebp
	inc	ebx
$LN13@jstr:
	mov	BYTE PTR [ecx+edi], al
	inc	edi
	jmp	SHORT $LN43@jstr
$LN7@jstr:
	mov	BYTE PTR [ecx+edi], al
	inc	edi
	inc	esi
	inc	ebp
	inc	ebx
$LN43@jstr:
	mov	DWORD PTR _z$[esp+36], edi
$LN8@jstr:
	cmp	esi, DWORD PTR _e$[esp+32]
	jb	$LL2@jstr
$LN41@jstr:
	pop	ebp
	pop	ebx
$LN21@jstr:
	mov	eax, DWORD PTR _n$[esp+24]
	mov	BYTE PTR [ecx+edi], 0
	mov	DWORD PTR [eax], edi
	mov	eax, ecx
	jmp	SHORT $LN1@jstr
$LN5@jstr:
	xor	eax, eax
$LN1@jstr:
	pop	edi
	pop	esi
	add	esp, 20					; 00000014H
	ret	0
_jstr	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _pu
_TEXT	SEGMENT
_o$ = 8							; size = 4
_n$ = 12						; size = 4
_c$ = 16						; size = 4
_pu	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 23
	mov	ecx, DWORD PTR _n$[esp-4]
	mov	eax, DWORD PTR _c$[esp-4]
	push	esi
	mov	esi, DWORD PTR _o$[esp]
	push	edi
	mov	edi, DWORD PTR [ecx]
	cmp	eax, 128				; 00000080H
	jae	SHORT $LN2@pu
	mov	BYTE PTR [edi+esi], al
	jmp	SHORT $LN11@pu
$LN2@pu:
	push	ebx
	mov	bl, al
	mov	edx, eax
	and	bl, 63					; 0000003fH
	shr	edx, 6
	or	bl, 128					; 00000080H
	cmp	eax, 2048				; 00000800H
	jae	SHORT $LN4@pu
	or	dl, 192					; 000000c0H
	mov	BYTE PTR [esi+edi], dl
	jmp	SHORT $LN10@pu
$LN4@pu:
	shr	eax, 12					; 0000000cH
	and	dl, 63					; 0000003fH
	or	al, 224					; 000000e0H
	mov	BYTE PTR [esi+edi], al
	mov	eax, DWORD PTR [ecx]
	inc	eax
	or	dl, 128					; 00000080H
	mov	DWORD PTR [ecx], eax
	mov	BYTE PTR [eax+esi], dl
$LN10@pu:
	mov	eax, DWORD PTR [ecx]
	inc	eax
	mov	DWORD PTR [ecx], eax
	mov	BYTE PTR [eax+esi], bl
	pop	ebx
$LN11@pu:
	inc	DWORD PTR [ecx]
	pop	edi
	pop	esi
	ret	0
_pu	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _hv
_TEXT	SEGMENT
_c$ = 8							; size = 1
_hv	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 22
	mov	cl, BYTE PTR _c$[esp-4]
	lea	eax, DWORD PTR [ecx-48]
	cmp	al, 9
	ja	SHORT $LN3@hv
	movzx	eax, cl
	sub	eax, 48					; 00000030H
	ret	0
$LN3@hv:
	lea	eax, DWORD PTR [ecx-97]
	cmp	al, 5
	ja	SHORT $LN4@hv
	movzx	eax, cl
	sub	eax, 87					; 00000057H
	ret	0
$LN4@hv:
	lea	eax, DWORD PTR [ecx-65]
	cmp	al, 5
	ja	SHORT $LN5@hv
	movzx	eax, cl
	sub	eax, 55					; 00000037H
	ret	0
$LN5@hv:
	or	eax, -1
	ret	0
_hv	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _mkout
_TEXT	SEGMENT
_slash$1$ = -8						; size = 4
tv598 = -4						; size = 4
tv602 = -4						; size = 4
_i$ = 8							; size = 4
_sl$1$ = 8						; size = 4
_e$ = 12						; size = 4
_mkout	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 20
	push	ecx
	push	ecx
	push	ebx
	push	ebp
	mov	ebp, DWORD PTR _i$[esp+12]
	push	esi
	xor	esi, esi
	push	edi
	mov	ecx, esi
	cmp	WORD PTR [ebp], si
	je	SHORT $LN22@mkout
$LL21@mkout:
	inc	ecx
	cmp	WORD PTR [ebp+ecx*2], si
	jne	SHORT $LL21@mkout
$LN22@mkout:
	or	eax, -1
	mov	DWORD PTR _sl$1$[esp+20], esi
	mov	DWORD PTR _slash$1$[esp+24], eax
	mov	ebx, esi
	mov	eax, DWORD PTR _e$[esp+20]
	or	edi, -1
	cmp	BYTE PTR [eax], bl
	je	SHORT $LN3@mkout
$LL2@mkout:
	inc	ebx
	cmp	BYTE PTR [eax+ebx], 0
	jne	SHORT $LL2@mkout
	mov	DWORD PTR _sl$1$[esp+20], ebx
$LN3@mkout:
	mov	edx, esi
	test	ecx, ecx
	je	SHORT $LN17@mkout
	push	46					; 0000002eH
	pop	ebx
$LL34@mkout:
	movzx	eax, WORD PTR [ebp+edx*2]
	mov	DWORD PTR tv602[esp+24], eax
	cmp	eax, 92					; 0000005cH
	je	SHORT $LN35@mkout
	cmp	eax, 47					; 0000002fH
	jne	SHORT $LN36@mkout
$LN35@mkout:
	mov	DWORD PTR _slash$1$[esp+24], edx
$LN36@mkout:
	cmp	WORD PTR tv602[esp+24], bx
	mov	eax, edx
	cmovne	eax, edi
	inc	edx
	mov	edi, eax
	cmp	edx, ecx
	jb	SHORT $LL34@mkout
	mov	ebx, DWORD PTR _sl$1$[esp+20]
	cmp	edi, -1
	je	SHORT $LN17@mkout
	mov	eax, DWORD PTR _slash$1$[esp+24]
	cmp	eax, -1
	je	SHORT $LN16@mkout
	cmp	edi, eax
	jae	SHORT $LN16@mkout
$LN17@mkout:
	mov	edi, ecx
$LN16@mkout:
	lea	eax, DWORD PTR [edi+ebx]
	mov	DWORD PTR tv598[esp+24], eax
	lea	eax, DWORD PTR [eax*2+4]
	push	eax
	call	_A
	mov	ebx, eax
	pop	ecx
	test	ebx, ebx
	je	SHORT $LN1@mkout
$LN18@mkout:
	mov	eax, esi
	test	edi, edi
	je	SHORT $LN8@mkout
	cmp	edi, 8
	jb	SHORT $LN56@mkout
	lea	ecx, DWORD PTR [edi+edi]
	lea	eax, DWORD PTR [ebp-2]
	lea	edx, DWORD PTR [ecx-2]
	add	eax, ecx
	add	edx, ebx
	cmp	ebx, eax
	ja	SHORT $LN41@mkout
	cmp	edx, ebp
	jae	SHORT $LN58@mkout
$LN41@mkout:
	push	ecx
	push	ebp
	push	ebx
	call	_cp
	add	esp, 12					; 0000000cH
	jmp	SHORT $LN8@mkout
$LN58@mkout:
	mov	eax, esi
$LN56@mkout:
	mov	edx, edi
	lea	ecx, DWORD PTR [ebx+eax*2]
	sub	ebp, ebx
	sub	edx, eax
$LL39@mkout:
	mov	ax, WORD PTR [ecx+ebp]
	mov	WORD PTR [ecx], ax
	lea	ecx, DWORD PTR [ecx+2]
	sub	edx, 1
	jne	SHORT $LL39@mkout
$LN8@mkout:
	mov	edx, DWORD PTR _sl$1$[esp+20]
	push	46					; 0000002eH
	pop	eax
	mov	WORD PTR [ebx+edi*2], ax
	test	edx, edx
	je	SHORT $LN11@mkout
	inc	edi
	lea	ecx, DWORD PTR [ebx+edi*2]
	mov	edi, DWORD PTR _e$[esp+20]
$LL42@mkout:
	movsx	ax, BYTE PTR [edi+esi]
	inc	esi
	mov	WORD PTR [ecx], ax
	lea	ecx, DWORD PTR [ecx+2]
	cmp	esi, edx
	jb	SHORT $LL42@mkout
$LN11@mkout:
	mov	eax, DWORD PTR tv598[esp+24]
	xor	ecx, ecx
	mov	WORD PTR [ebx+eax*2+2], cx
	mov	eax, ebx
$LN1@mkout:
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	pop	ecx
	pop	ecx
	ret	0
_mkout	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _wl
_TEXT	SEGMENT
_s$ = 8							; size = 4
_wl	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 20
	mov	ecx, DWORD PTR _s$[esp-4]
	xor	edx, edx
	mov	eax, edx
	cmp	WORD PTR [ecx], dx
	je	SHORT $LN3@wl
$LL2@wl:
	inc	eax
	cmp	WORD PTR [ecx+eax*2], dx
	jne	SHORT $LL2@wl
$LN3@wl:
	ret	0
_wl	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _ext
_TEXT	SEGMENT
_p$ = 8							; size = 4
_n$ = 12						; size = 4
_ext	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 19
	mov	edx, DWORD PTR _n$[esp-4]
	mov	ecx, DWORD PTR _p$[esp-4]
	cmp	edx, 4
	jb	SHORT $LN2@ext
	cmp	BYTE PTR [ecx], 102			; 00000066H
	jne	SHORT $LN8@ext
	cmp	BYTE PTR [ecx+1], 76			; 0000004cH
	jne	SHORT $LN4@ext
	cmp	BYTE PTR [ecx+2], 97			; 00000061H
	jne	SHORT $LN4@ext
	cmp	BYTE PTR [ecx+3], 67			; 00000043H
	jne	SHORT $LN4@ext
	mov	eax, OFFSET ??_C@_04FJJKFLMH@flac@
	ret	0
$LN2@ext:
	cmp	edx, 3
	jb	SHORT $LN3@ext
$LN8@ext:
	cmp	BYTE PTR [ecx], 73			; 00000049H
	jne	SHORT $LN7@ext
	cmp	BYTE PTR [ecx+1], 68			; 00000044H
	jne	SHORT $LN4@ext
	cmp	BYTE PTR [ecx+2], 51			; 00000033H
	je	SHORT $LN9@ext
$LN4@ext:
	cmp	edx, 8
	jb	SHORT $LN5@ext
	cmp	BYTE PTR [ecx+4], 102			; 00000066H
	jne	SHORT $LN5@ext
	cmp	BYTE PTR [ecx+5], 116			; 00000074H
	jne	SHORT $LN5@ext
	cmp	BYTE PTR [ecx+6], 121			; 00000079H
	jne	SHORT $LN5@ext
	cmp	BYTE PTR [ecx+7], 112			; 00000070H
	mov	eax, OFFSET ??_C@_03EIHDBIJH@m4a@
	mov	edx, OFFSET ??_C@_03PDOMKJON@bin@
	cmovne	eax, edx
	ret	0
$LN3@ext:
	cmp	edx, 2
	jb	SHORT $LN5@ext
$LN7@ext:
	cmp	BYTE PTR [ecx], 255			; 000000ffH
	jne	SHORT $LN4@ext
	mov	al, BYTE PTR [ecx+1]
	and	al, 224					; 000000e0H
	cmp	al, 224					; 000000e0H
	jne	SHORT $LN4@ext
$LN9@ext:
	mov	eax, OFFSET ??_C@_03LHGNACFN@mp3@
	ret	0
$LN5@ext:
	mov	eax, OFFSET ??_C@_03PDOMKJON@bin@
	ret	0
_ext	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _st
_TEXT	SEGMENT
_p$ = 8							; size = 4
_n$ = 12						; size = 4
_s$ = 16						; size = 4
_st	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 18
	mov	ecx, DWORD PTR _s$[esp-4]
	xor	edx, edx
	push	esi
	cmp	BYTE PTR [ecx], dl
	je	SHORT $LN3@st
	mov	esi, DWORD PTR _p$[esp]
	sub	esi, ecx
$LL2@st:
	cmp	edx, DWORD PTR _n$[esp]
	jae	SHORT $LN8@st
	mov	al, BYTE PTR [esi+ecx]
	cmp	al, BYTE PTR [ecx]
	jne	SHORT $LN8@st
	inc	edx
	inc	ecx
	cmp	BYTE PTR [ecx], 0
	jne	SHORT $LL2@st
$LN3@st:
	xor	eax, eax
	inc	eax
	pop	esi
	ret	0
$LN8@st:
	xor	eax, eax
	pop	esi
	ret	0
_st	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _decaud
_TEXT	SEGMENT
_p$ = 8							; size = 4
_n$ = 12						; size = 4
_b$ = 16						; size = 4
_decaud	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 17
	push	esi
	mov	esi, DWORD PTR _n$[esp]
	test	esi, esi
	je	SHORT $LN3@decaud
	mov	edx, DWORD PTR _p$[esp]
	push	ebx
	mov	ebx, DWORD PTR _b$[esp+4]
	push	edi
	xor	edi, edi
	inc	edi
	sub	edi, edx
$LL4@decaud:
	lea	eax, DWORD PTR [edi+edx]
	movzx	eax, al
	movzx	ecx, BYTE PTR [eax+ebx]
	add	eax, ecx
	movzx	eax, al
	movzx	eax, BYTE PTR [eax+ebx]
	add	eax, ecx
	movzx	eax, al
	mov	al, BYTE PTR [eax+ebx]
	xor	BYTE PTR [edx], al
	inc	edx
	sub	esi, 1
	jne	SHORT $LL4@decaud
	pop	edi
	pop	ebx
$LN3@decaud:
	pop	esi
	ret	0
_decaud	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _box
_TEXT	SEGMENT
_k$ = 8
_n$ = 12
_b$ = 16
_box	PROC
	push	ebx
	push	ebp
	push	esi
	push	edi
	mov	esi, DWORD PTR _b$[esp+12]
	xor	eax, eax
$Linit_box:
	mov	BYTE PTR [esi+eax], al
	inc	eax
	cmp	eax, 256
	jb	SHORT $Linit_box
	xor	edi, edi
	xor	edx, edx
	xor	ebp, ebp
$Lloop_box:
	mov	eax, DWORD PTR _k$[esp+12]
	mov	bl, BYTE PTR [esi+edi]
	movzx	ecx, bl
	add	ecx, ebp
	movzx	eax, BYTE PTR [eax+edx]
	add	ecx, eax
	and	ecx, 255
	inc	edx
	cmp	edx, DWORD PTR _n$[esp+12]
	jb	SHORT $Lko_box
	xor	edx, edx
$Lko_box:
	mov	al, BYTE PTR [esi+ecx]
	mov	BYTE PTR [esi+edi], al
	inc	edi
	mov	BYTE PTR [esi+ecx], bl
	mov	ebp, ecx
	cmp	edi, 256
	jb	SHORT $Lloop_box
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	ret	0
_box	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _aes
_TEXT	SEGMENT
_a$ = -28						; size = 4
_kh$ = -24						; size = 4
_ob$ = -20						; size = 4
_pl$ = -16						; size = 4
_cb$ = -12						; size = 4
_g$2$ = -8						; size = 4
tv300 = -4						; size = 4
_i$ = 8							; size = 4
_il$ = 12						; size = 4
_r$1$ = 12						; size = 4
_k$ = 16						; size = 4
_o$ = 20						; size = 4
_ol$ = 24						; size = 4
_aes	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 15
	sub	esp, 28					; 0000001cH
	push	ebx
	mov	ebx, DWORD PTR _il$[esp+28]
	xor	eax, eax
	mov	DWORD PTR _a$[esp+32], eax
	mov	DWORD PTR _kh$[esp+32], eax
	mov	DWORD PTR _ob$[esp+32], eax
	mov	DWORD PTR _cb$[esp+32], eax
	mov	DWORD PTR _pl$[esp+32], eax
	push	ebp
	mov	ebp, eax
	push	esi
	mov	esi, eax
	push	edi
	mov	edi, eax
	test	bl, 15					; 0000000fH
	jne	$LN1@aes
$LN5@aes:
	push	eax
	push	eax
	push	OFFSET ??_C@_17PJMHNJHG@?$AAA?$AAE?$AAS@
	lea	eax, DWORD PTR _a$[esp+56]
	push	eax
	call	_BCryptOpenAlgorithmProvider@16
	test	eax, eax
	js	$x$43
	push	0
	push	32					; 00000020H
	push	OFFSET ??_C@_1CA@GGHMBPCI@?$AAC?$AAh?$AAa?$AAi?$AAn?$AAi?$AAn?$AAg?$AAM?$AAo?$AAd?$AAe?$AAE?$AAC?$AAB@
	push	OFFSET ??_C@_1BK@BCJKEJJO@?$AAC?$AAh?$AAa?$AAi?$AAn?$AAi?$AAn?$AAg?$AAM?$AAo?$AAd?$AAe@
	push	DWORD PTR _a$[esp+60]
	call	_BCryptSetProperty@20
	test	eax, eax
	js	$x$43
	push	0
	lea	eax, DWORD PTR _cb$[esp+48]
	push	eax
	push	4
	lea	eax, DWORD PTR _ob$[esp+56]
	push	eax
	push	OFFSET ??_C@_1BK@GPNIFMAA@?$AAO?$AAb?$AAj?$AAe?$AAc?$AAt?$AAL?$AAe?$AAn?$AAg?$AAt?$AAh@
	push	DWORD PTR _a$[esp+64]
	call	_BCryptGetProperty@24
	test	eax, eax
	js	$x$43
	push	DWORD PTR _ob$[esp+44]
	call	_A
	push	ebx
	mov	edi, eax
	call	_A
	mov	esi, eax
	pop	ecx
	pop	ecx
	test	edi, edi
	je	$x$43
	test	esi, esi
	je	$x$43
	push	0
	push	16					; 00000010H
	push	DWORD PTR _k$[esp+48]
	lea	eax, DWORD PTR _kh$[esp+56]
	push	DWORD PTR _ob$[esp+56]
	push	edi
	push	eax
	push	DWORD PTR _a$[esp+68]
	call	_BCryptGenerateSymmetricKey@28
	test	eax, eax
	js	$x$43
	xor	ecx, ecx
	lea	eax, DWORD PTR _pl$[esp+44]
	push	ecx
	push	eax
	push	ebx
	push	esi
	push	ecx
	push	ecx
	push	ecx
	push	ebx
	push	DWORD PTR _i$[esp+72]
	push	DWORD PTR _kh$[esp+80]
	call	_BCryptDecrypt@40
	test	eax, eax
	js	SHORT $x$43
	mov	ecx, DWORD PTR _pl$[esp+44]
	xor	ebp, ebp
	inc	ebp
	mov	DWORD PTR _r$1$[esp+40], ebp
	test	ecx, ecx
	je	SHORT $LN16@aes
	mov	dl, BYTE PTR [esi+ecx-1]
	test	dl, dl
	je	SHORT $LN16@aes
	cmp	dl, 16					; 00000010H
	ja	SHORT $LN16@aes
	movzx	eax, dl
	cmp	eax, ecx
	ja	SHORT $LN16@aes
	mov	ebx, ecx
	mov	DWORD PTR _g$2$[esp+44], ebp
	sub	ebx, eax
	mov	ebp, ebx
	mov	DWORD PTR tv300[esp+44], ebx
	cmp	ebp, ecx
	jae	SHORT $LN24@aes
	mov	ebx, DWORD PTR _g$2$[esp+44]
$LL4@aes:
	xor	eax, eax
	cmp	BYTE PTR [esi+ebp], dl
	cmove	eax, ebx
	inc	ebp
	mov	ebx, eax
	cmp	ebp, ecx
	jb	SHORT $LL4@aes
	test	ebx, ebx
	mov	ebx, DWORD PTR tv300[esp+44]
	je	SHORT $LN25@aes
$LN24@aes:
	mov	ecx, ebx
	mov	DWORD PTR _pl$[esp+44], ecx
$LN25@aes:
	mov	ebp, DWORD PTR _r$1$[esp+40]
$LN16@aes:
	mov	eax, DWORD PTR _o$[esp+40]
	mov	DWORD PTR [eax], esi
	xor	esi, esi
	mov	eax, DWORD PTR _ol$[esp+40]
	mov	DWORD PTR [eax], ecx
$x$43:
	cmp	DWORD PTR _kh$[esp+44], 0
	je	SHORT $LN17@aes
	push	DWORD PTR _kh$[esp+44]
	call	_BCryptDestroyKey@4
$LN17@aes:
	cmp	DWORD PTR _a$[esp+44], 0
	je	SHORT $LN18@aes
	push	0
	push	DWORD PTR _a$[esp+48]
	call	_BCryptCloseAlgorithmProvider@8
$LN18@aes:
	push	edi
	call	_F
	push	esi
	call	_F
	pop	ecx
	pop	ecx
	mov	eax, ebp
$LN1@aes:
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	add	esp, 28					; 0000001cH
	ret	0
_aes	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _wr2
_TEXT	SEGMENT
_w$ = -4						; size = 4
_p$ = 8							; size = 4
_a$ = 12						; size = 4
_an$ = 16						; size = 4
_b$ = 20						; size = 4
_bn$ = 24						; size = 4
_wr2	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 14
	push	ebp
	mov	ebp, esp
	push	ecx
	push	esi
	push	edi
	xor	esi, esi
	push	esi
	push	esi
	push	2
	push	esi
	push	esi
	push	1073741824				; 40000000H
	push	DWORD PTR _p$[ebp]
	call	DWORD PTR __imp__CreateFileW@28
	mov	edi, eax
	cmp	edi, -1
	jne	SHORT $LN2@wr2
	xor	eax, eax
	jmp	SHORT $LN1@wr2
$LN2@wr2:
	push	ebx
	mov	ebx, DWORD PTR _an$[ebp]
	test	ebx, ebx
	je	SHORT $LN3@wr2
	push	esi
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	push	ebx
	push	DWORD PTR _a$[ebp]
	push	edi
	call	DWORD PTR __imp__WriteFile@20
	test	eax, eax
	je	SHORT $LN8@wr2
	cmp	DWORD PTR _w$[ebp], ebx
	jne	SHORT $LN8@wr2
$LN3@wr2:
	mov	ebx, DWORD PTR _bn$[ebp]
	test	ebx, ebx
	je	SHORT $LN5@wr2
	push	esi
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	push	ebx
	push	DWORD PTR _b$[ebp]
	push	edi
	call	DWORD PTR __imp__WriteFile@20
	test	eax, eax
	je	SHORT $LN8@wr2
	cmp	DWORD PTR _w$[ebp], ebx
	jne	SHORT $LN8@wr2
$LN5@wr2:
	xor	esi, esi
	inc	esi
$LN8@wr2:
	push	edi
	call	DWORD PTR __imp__CloseHandle@4
	mov	eax, esi
	pop	ebx
$LN1@wr2:
	pop	edi
	pop	esi
	leave
	ret	0
_wr2	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _rd
_TEXT	SEGMENT
_g$ = -12						; size = 4
_z$ = -8						; size = 8
_p$ = 8							; size = 4
_d$ = 12						; size = 4
_n$ = 16						; size = 4
_rd	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 13
	sub	esp, 12					; 0000000cH
	push	ebp
	push	esi
	xor	ebp, ebp
	push	ebp
	push	ebp
	push	3
	push	ebp
	push	1
	push	-2147483648				; 80000000H
	push	DWORD PTR _p$[esp+40]
	call	DWORD PTR __imp__CreateFileW@28
	mov	esi, eax
	cmp	esi, -1
	jne	SHORT $LN2@rd
	xor	eax, eax
	jmp	$LN1@rd
$LN2@rd:
	push	ebx
	push	edi
	lea	eax, DWORD PTR _z$[esp+28]
	push	eax
	push	esi
	call	DWORD PTR __imp__GetFileSizeEx@8
	test	eax, eax
	je	SHORT $LN4@rd
	mov	edx, DWORD PTR _z$[esp+28]
	mov	ecx, edx
	mov	eax, DWORD PTR _z$[esp+32]
	add	ecx, -1
	adc	eax, -1
	cmp	eax, ebp
	ja	SHORT $LN4@rd
	jb	SHORT $LN10@rd
	cmp	ecx, 2147483646				; 7ffffffeH
	ja	SHORT $LN4@rd
$LN10@rd:
	mov	ebx, DWORD PTR _n$[esp+24]
	push	edx
	mov	DWORD PTR [ebx], edx
	call	_A
	mov	edi, DWORD PTR _d$[esp+28]
	pop	ecx
	mov	DWORD PTR [edi], eax
	test	eax, eax
	je	SHORT $LN4@rd
	push	ebp
	lea	ecx, DWORD PTR _g$[esp+32]
	push	ecx
	push	DWORD PTR [ebx]
	push	eax
	push	esi
	call	DWORD PTR __imp__ReadFile@20
	test	eax, eax
	je	SHORT $LN7@rd
	mov	ecx, DWORD PTR _g$[esp+28]
	cmp	ecx, DWORD PTR [ebx]
	jne	SHORT $LN7@rd
	push	esi
	call	DWORD PTR __imp__CloseHandle@4
	xor	eax, eax
	inc	eax
	jmp	SHORT $LN18@rd
$LN7@rd:
	push	esi
	call	DWORD PTR __imp__CloseHandle@4
	push	DWORD PTR [edi]
	call	_F
	pop	ecx
	mov	DWORD PTR [edi], ebp
	jmp	SHORT $LN20@rd
$LN4@rd:
	push	esi
	call	DWORD PTR __imp__CloseHandle@4
$LN20@rd:
	xor	eax, eax
$LN18@rd:
	pop	edi
	pop	ebx
$LN1@rd:
	pop	esi
	pop	ebp
	add	esp, 12					; 0000000cH
	ret	0
_rd	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _xo
_TEXT	SEGMENT
_p$ = 8							; size = 4
_n$ = 12						; size = 4
_x$ = 16						; size = 1
_xo	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 12
	mov	eax, DWORD PTR _n$[esp-4]
	test	eax, eax
	je	SHORT $LN6@xo
	mov	dl, BYTE PTR _x$[esp-4]
	mov	ecx, DWORD PTR _p$[esp-4]
$LL2@xo:
	xor	BYTE PTR [ecx], dl
	inc	ecx
	sub	eax, 1
	jne	SHORT $LL2@xo
$LN6@xo:
	ret	0
_xo	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _eq
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_n$ = 16						; size = 4
_eq	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 12
	mov	edx, DWORD PTR _n$[esp-4]
	push	esi
	push	edi
	test	edx, edx
	je	SHORT $LN8@eq
	mov	edi, DWORD PTR _a$[esp+4]
	mov	esi, DWORD PTR _b$[esp+4]
	sub	edi, esi
$LL2@eq:
	mov	cl, BYTE PTR [edi+esi]
	dec	edx
	mov	al, BYTE PTR [esi]
	inc	esi
	cmp	cl, al
	jne	SHORT $LN7@eq
	test	edx, edx
	jne	SHORT $LL2@eq
$LN8@eq:
	xor	eax, eax
	inc	eax
$LN1@eq:
	pop	edi
	pop	esi
	ret	0
$LN7@eq:
	xor	eax, eax
	jmp	SHORT $LN1@eq
_eq	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _s32
_TEXT	SEGMENT
_p$ = 8							; size = 4
_v$ = 12						; size = 4
_s32	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 11
	mov	edx, DWORD PTR _v$[esp-4]
	mov	eax, edx
	mov	ecx, DWORD PTR _p$[esp-4]
	shr	eax, 21					; 00000015H
	and	al, 127					; 0000007fH
	mov	BYTE PTR [ecx], al
	mov	eax, edx
	shr	eax, 14					; 0000000eH
	and	al, 127					; 0000007fH
	mov	BYTE PTR [ecx+1], al
	mov	eax, edx
	shr	eax, 7
	and	dl, 127					; 0000007fH
	and	al, 127					; 0000007fH
	mov	BYTE PTR [ecx+3], dl
	mov	BYTE PTR [ecx+2], al
	ret	0
_s32	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _b32
_TEXT	SEGMENT
_p$ = 8
_v$ = 12
_b32	PROC
	mov	eax, DWORD PTR _v$[esp-4]
	mov	ecx, DWORD PTR _p$[esp-4]
	bswap	eax
	mov	DWORD PTR [ecx], eax
	ret	0
_b32	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _r32
_TEXT	SEGMENT
_p$ = 8
_r32	PROC
	mov	edx, DWORD PTR _p$[esp-4]
	mov	eax, DWORD PTR [edx]
	ret	0
_r32	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _F
_TEXT	SEGMENT
_p$ = 8							; size = 4
_F	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 10
	cmp	DWORD PTR _p$[esp-4], 0
	je	SHORT $LN2@F
	push	DWORD PTR _p$[esp-4]
	push	0
	call	DWORD PTR __imp__GetProcessHeap@0
	push	eax
	call	DWORD PTR __imp__HeapFree@12
$LN2@F:
	ret	0
_F	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _A
_TEXT	SEGMENT
_n$ = 8							; size = 4
_A	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 10
	xor	eax, eax
	inc	eax
	cmp	DWORD PTR _n$[esp-4], 0
	cmovne	eax, DWORD PTR _n$[esp-4]
	push	eax
	push	0
	call	DWORD PTR __imp__GetProcessHeap@0
	push	eax
	call	DWORD PTR __imp__HeapAlloc@12
	ret	0
_A	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _cp
_TEXT	SEGMENT
_d$ = 8							; size = 4
_s$ = 12						; size = 4
_n$ = 16						; size = 4
_cp	PROC						; COMDAT
; File D:\工具\ncm\测试区\源码\ncmmini.c
; Line 9
	mov	ecx, DWORD PTR _n$[esp-4]
	test	ecx, ecx
	je	SHORT $LN6@cp
	mov	edx, DWORD PTR _s$[esp-4]
	push	esi
	mov	esi, DWORD PTR _d$[esp]
	sub	esi, edx
$LL2@cp:
	mov	al, BYTE PTR [edx]
	mov	BYTE PTR [esi+edx], al
	inc	edx
	sub	ecx, 1
	jne	SHORT $LL2@cp
	pop	esi
$LN6@cp:
	ret	0
_cp	ENDP
_TEXT	ENDS
END
